FROM internetofwater/qendpoint

WORKDIR /app

COPY iow-prefixes.sparql .
COPY loadDataFrinkRenci.sh .
RUN chmod +x loadDataFrinkRenci.sh

RUN apt-get install rclone

#ARG HDT_BASE=wikidata_truthy
#ENV HDT_BASE ${HDT_BASE}

EXPOSE 1234
ENTRYPOINT ["/usr/bin/env"]

CMD ["/bin/sh", "-c", "sleep 10 && /app/loadDataFrinkRenci.sh && sleep 60 && java -jar -Xmx${MEM_SIZE} qendpoint.jar"]
