FROM internetofwater/qendpoint

WORKDIR /app

COPY iow-prefixes.sparql /app/

ADD https://storage.googleapis.com/geoconnex-graph/index_dev.hdt /app/qendpoint/index-hdt/index_dev.hdt
ADD https://storage.googleapis.com/geoconnex-graph/index_dev.hdt.index.v1-1 /app/qendpoint/index-hdt/index_dev.hdt.index.v1-1

EXPOSE 1234
ENTRYPOINT ["/usr/bin/env"]

CMD ["/bin/sh", "-c", "java -jar -Xmx${MEM_SIZE} qendpoint.jar"]
